name: XivXrat Auto Builder

on:
  push:
    branches: [ "main" ] # Robot jalan setiap Tuan klik Commit/Push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK (Release Mode)
      run: ./gradlew assembleDebug

    - name: Upload APK to GitHub Release
      uses: actions/upload-artifact@v4
      with:
        name: XivXrat-GoogleService-APK
        path: app/build/outputs/apk/debug/app-debug.apk
