name: XivXrat-Final-Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 11 # Menggunakan JDK 11 agar lebih stabil
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.0 # PAKSA PAKAI VERSI 8.0

    - name: Build APK
      run: gradle assembleDebug --stacktrace # Tambah stacktrace biar kalau error kelihatan detailnya

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: XivXrat-APK
        path: app/build/outputs/apk/debug/app-debug.apk
