name: Build XivXrat APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Update ke v4 (Node 20 support)

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate Missing Wrapper Jar
      run: |
        # Download gradle portable untuk memancing wrapper
        wget https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
        unzip -q gradle-8.0.2-bin.zip
        export PATH=$PATH:$(pwd)/gradle-8.0.2/bin
        
        # Eksekusi perintah sakti buat bikin file .jar yang hilang
        gradle wrapper --gradle-version 8.0.2
        
        # Kasih izin eksekusi
        chmod +x gradlew

    - name: Build XivXrat APK
      run: ./gradlew assembleRelease --stacktrace
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4 # Update ke v4
      with:
        name: XivXrat-Release
        path: app/build/outputs/apk/release/*.apk
